name: Build a static website and Publish to pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build artifact
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        env:
          CI: false
        run: |
          npm ci
          npm run build --if-present

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
